# Here is where the MySQL connection can be configured.
# (Note: Database tables are created and managed automatically. There is also no MySQL conversion to YAML file; therefore, use at your own risk.)
mysql-connection:
  # If this option is enabled, HyperDrive will enable cross-server teleportation and MySQL warp saving/loading.
  use-mysql: false
  # Determines whether the connection should utilize SSL.
  use-ssl: false
  # Make sure this option is disabled if you plan to only use MySQL without cross-server features.
  cross-server: true
  # If a warp's IP is found blank or null, its IP will be replaced with this IP similar to a backup. This IP should be your EXACT server's IP WITHOUT THE PORT.
  default-ip: "127.0.0.1"
  # Below, define your MySQL information. THE DEFINED DATABASE MUST ALREADY EXIST.
  database-name: "hyperdrive"
  host: "localhost"
  port: 3306
  username: "root"
  password: ""

# Here is where everything that is general can be configured
general-section:
  # If this option is enabled, Vault will be hooked into and be used for item which require a fee.
  use-vault: false
  # If this option is enabled, the console will be notified every time the warps are automatically saved.
  auto-save-log: true
  # This is the interval of the warp auto-save in seconds.
  auto-save-interval: 900
  # Whether or not warps will be cleaned based on inactivity.
  warp-cleaner: false
  # The time a player must have not logged in or been seen in seconds before their warp is removed.
  warp-clean-time: 604800
  # If this is enabled, players will be forcefully sent to spawn on join (First join spawn will be skipped if invalid).
  force-spawn: true
  # If this is enabled, players will be forced back to spawn on death.
  force-death-spawn: true
  # If this is enabled and the option above is enabled, the player will only be sent to the first join spawn on there first log-in.
  # (Note: If false and the option above is true, the player will be sent to a spawn regardless even if they have already joined before)
  force-only-first-join: true
  # The commands in the list below will be initiated in the console when a player joins for the very first time.
  first-join-commands:
    - "tell {player} Welcome {player} this is a command that has been sent to you for joining for the very first time!"
  # If this option is enabled, all warps found in the existing Essentials folder will be converted into HyperDrive warps.
  # (Note: No essentials warps will be removed; therefore, please disable this option after the conversion is complete.)
  essentials-converter: false
  # If using the essentials converter, set this to the name of your installed essentials plugin.
  essentials-name: "Essentials"
  # If this is disabled, all plugin hooks will only be checked to see if a claim exists at that location rather than ownership.
  claim-ownership-checks: true
  # This is what the user must type to forcefully cancel a chat interaction.
  chat-interaction-cancel: "cancel"
  # This is the format that is used for toggle based options. These will be the two values used when a option is either enabled or disabled (Please use the format <enable>:<disable>).
  # (Note: If the format is incorrect the plugin will use the values "Enabled" and "Disabled" by default).
  option-toggle-format: "Enabled:Disabled"
  # This is the default amount of warps a user can own.
  default-warp-limit: 3
  # These are the sounds used throughout the plugin. These will need to be adjusted based on the server's Minecraft version.
  # Latest Sound List: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
  # Sound List (Legacy): http://docs.codelanx.com/Bukkit/1.8/org/bukkit/Sound.html
  global-sounds:
    # This is the sound played when a player is teleported through things like warps.
    teleport: "ENTITY_ENDERMAN_TELEPORT"
    # This is the sound played when a player is teleported through a standalone teleportation command.
    standalone-teleport: "ENTITY_ENDERMAN_TELEPORT"
  # This is the color that will be placed in front of the header of newly created HyperDrive signs.
  # (Note: ONLY use color codes)
  sign-header-color: "&d"
  # This is a list of all commands that will be ran anytime a warp is used by any means.
  # Avoid using slashes (/) and always end a command with either :PLAYER or :CONSOLE to determine how it is sent.
  global-warp-commands: []
  # Here you can implement unlimited custom aliases that run commands. Use the format <alias:command:sender>.
  # You can use the placeholder {player}. (Note: Set the sender to PLAYER for the command to be re-sent as a
  # player and CONSOLE to send as console. Don't use the initial command / if it is set to CONSOLE)
  custom-alias-commands: []
  # Worlds found in this list will not allow warp creation.
  world-blacklist: []

# Here is where filters can be customized to remove unwanted symbols or words from use in the plugin's features.
filter-section:
  # Strings within the global filter will be remove from warp names, descriptions, and other similar textual features. (Case sensitive)
  # (Note: Phrases can be implemented into this list as well. The list can also be changed to a vertical format like
  # other lists in the configuration.)
  global-filter: ["fuck", "shit", "cunt", "fag", "faggot", "bitch", "dick", "damn", "www.", ".com", ".net"]
  # Materials in this list will be avoided while a player is undergoing teleportation. If any of these material are encountered, the teleportation will return NOT SAFE.
  # (NOTE: The material name can be generalized, for example, the value "leaves" will detect all materials that have that value in their name)
  # This format is what needs to be followed to coordinate specific data values: <material>:<durability>
  forbidden-materials:
    - "WATER"
    - "LAVA"
    - "LILY"
    - "AIR"
    - "LEAVES"

# Here is where everything related to teleportation can be customize.
teleportation-section:
  # This is how long after any teleportation done by HyperDrive will grant the player invulnerability to ALL damage.
  # (Note: Set this value to -1 to disable.)
  invulnerability-duration: 5
  # This is the general teleportation cooldown that a player must wait before teleporting again (In seconds).
  cooldown-duration: 15
  # This is the TPA cooldown that a player must wait before using the TPA command again (In seconds).
  tpa-cooldown: 15
  # If the player teleports while in a vehicle should they be dismounted and teleported?
  # (Note: The mount will be teleported as well, but half a second after to prevent faulty chunk loading)
  teleport-vehicles: true
  # This is the duration of how long a TPA request will stay alive. After the duration the request can no longer be accepted or denied.
  teleport-ask-duration: 10
  # This is the duration of how long a group request will stay alive. After the duration the request can no longer be accepted or denied.
  group-request-duration: 12
  # If this option is enabled, players will have their teleportation process cancelled upon taking damage from any source.
  damage-cancellation: true
  # If this option is enabled, players will have their teleportation process cancelled upon moving.
  move-cancellation: true
  # This is the duration the player must wait before engaging warp teleportation (In seconds).
  warp-delay-duration: 10
  # This is the duration the player must wait before engaging a standalone teleport (In seconds).
  standalone-delay-duration: 10
  # These are the title and sub-title that are sent to the player after they are teleported (Note: Set to "" to disable).
  teleport-title: "&eYou have been teleported"
  teleport-sub-title: "&eto the &a{warp} &ewarp."
  # These are the title and sub-title that are sent to the player 5 seconds before the teleportation is engaged (Note: Set to "" to disable).
  delay-title: "&eTeleportation will be engaged"
  delay-sub-title: "&ein approximately &a{duration} &eseconds."
  # These are the title and sub-title that are sent to the player when the teleportation process has begun (Note: Set to "" to disable).
  start-title: "&eYou will be teleported to"
  start-sub-title: "&ethe &a{warp} &ein approximately &a{duration} &eseconds."
  # This is the message display on the player's action bar while the teleportation process is counting down (Set to "" to disable).
  delay-bar-message: "&eTeleportation will engage in: &r{progress} &e- &a{duration-left} &eSeconds"
  # This is the message display on the player's action bar when a teleportation process has begun (Set to "" to disable).
  start-bar-message: "&eTeleportation to the warp &a{warp} &ewill engage in &a{duration} &eseconds."
  # This is the message display on the player's action bar when a teleportation process has completed (Set to "" to disable).
  teleport-bar-message: "&eYou have been teleported to the warp &a{warp}&e."

# Here is where everything related to random teleportation can be customize.
random-teleport-section:
  # How long in between random teleportation processes should the player have to wait before beginning another in seconds.
  cooldown: 10
  # This is the duration the player must wait before engaging random teleportation (In seconds).
  delay-duration: 10
  # These are the title and sub-title that are sent to the player 5 seconds before the random teleportation is engaged (Note: Set to "" to disable).
  delay-title: "&eRandom teleportation will be engaged"
  delay-sub-title: "&ein approximately &a{duration} &eseconds."
  # These are the title and sub-title that are sent to the player when the random teleportation process has begun (Note: Set to "" to disable).
  start-title: "&eYou will be randomly teleported"
  start-sub-title: "&ein approximately &a{duration} &eseconds."
  # This is the message display on the player's action bar while the random teleportation process is counting down (Set to "" to disable).
  delay-bar-message: "&eRandom teleportation will engage in: &r{progress} &e- &a{duration-left} &eSeconds"
  # This is the message display on the player's action bar when a random teleportation process has begun (Set to "" to disable).
  start-bar-message: "&eRandom teleportation will engage in &a{duration} &eseconds."
  # These are the worlds where RTP will not be allowed to take a player.
  forbidden-worlds:
    - "world_the_end"
  # This is how many times the random teleportation feature can attempt to teleport the player before aborting the task.
  # (Note: The higher the slower, recommended value is below 30 if "can-load-chunks" is enabled, set to -1 for unlimited)
  max-tries: 300
  # If a biome name is contained in this list, that biome will be avoided.
  # Here is a list of biomes: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/block/Biome.html
  # (NOTE: Biome names can be generalized, for example, if the value "OCEAN" is entered all biomes containing the name "OCEAN" will be blacklisted.)
  biome-blacklist:
    - "OCEAN"

warp-icon-section:
  # This is the sound that is played when a warp icon is selected. This option can be set to "" to disable.
  # Latest Sound List: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
  # Sound List (Legacy): http://docs.codelanx.com/Bukkit/1.8/org/bukkit/Sound.html
  click-sound: "UI_BUTTON_CLICK"
  # This message is used in place of placeholders in the warp icon that were unable to be retrieved.
  invalid-retrieval: "&cUnable to be retrieved at this time."
  # This is the default status a newly created warp is set to.
  # Current Status Values: [PUBLIC, PRIVATE, SERVER]
  default-status: "PUBLIC"
  # This is the default material a warp icon will be set to upon creation.
  default-icon-material: "PLAYER_HEAD,0,1"
  # When the player sets the description to only this symbol, the description will be cleared.
  description-clear-symbol: "-"
  # This is the maximum word count per description line when setting it. All words past this count will be
  # wrapped to the next line unless it is a long word to completely and the word is under .
  description-line-cap: 5
  # If a long word exceeds this length in characters, it will be trimmed to this length for cleanliness.
  # (NOTE: This can be set to -1 to disable this check)
  long-word-wrap: 16
  # This is the default description that is set to a newly created warp.
  default-description: "This is the default HyperDrive warp description. (Note: This can be changed inside the edit menu)"
  # This is the lore the warp icon is given inside of menus.
  # Current Placeholders:
  # {description} - replaces the line with the first description line while adding the remaining lines below it.
  # {status} - replaced with the warp's current status.
  # {usage-price} - replaced with the warp's usage price.
  # {traffic} - replaced with the warp's traffic count.
  # {creation-date} - replaced with the warp's creation date.
  # {owner} - replaced with the warp owner's name.
  # {assistant-count}- replaced with warp's assistants count.
  # {theme} - replaced with the name of the icon theme currently in use by the warp.
  # {animation-set} - replaced with the name of the animation set.
  # {list-count} - The total of players in the player list.
  # {assistant-count} - The total of assistant players.
  # {likes} - The total likes.
  # {dislikes} - The total dislikes.
  # {like-bar} - The like ratio as a progress bar.
  ###
  # Unlike other formats in this lore format you are able to hide/show certain lines based on events. To hide/show a line based
  # on an event you must simply ensure that the line contains an event placeholder. Below are the currently available placeholders:
  # (Note: The placeholder can be anywhere in the line it just needs to be exactly how it is show below to be detected.
  # Only one event will be read and used all extra events will be ignored.)
  ###
  # {is-owner} - Only displays the line if the player is the owner of the warp.
  # {has-access} - Only displays the line if the player has access to use the warp.
  # {no-access} - Only displays the line if the player does NOT have access to use the warp.
  # {can-edit} - Only displays the line if the player can edit the warp.
  # {is-private} - Only displays if the warp's status is set to PRIVATE.
  # {is-public} - Only displays if the warp's status is set to PUBLIC.
  # {is-admin} - Only displays if the warp's status is set to ADMIN.
  list-lore-format:
    - "{description}"
    - ""
    - "{no-access}&cYou don't have access to use this warp."
    - "{has-access}&a(Left-Click) &eBegin the teleportation process."
    - "{has-access}&a(Right-Click) &eBegin the group teleportation process."
    - "{has-access}&a(Shift + Left-Click) &eBegin the warp rating process."
    - "{can-edit}&a(Shift + Right-Click) &eBegin the warp edit process."
    - ""
    - "&7It will cost &e${usage-price} &7to use this warp."
    - "&a\u2714 &e{likes} &r{like-bar} &e{dislikes} &c\u2716"
    - ""
    - "&7Owner: &e{owner}"
    - "&7Visits: &e{traffic}"
    - ""
    - "&7Created: &e{creation-date}"
    - "&7This is a &e{status} &7warp."

# Here is where everything related to animation can be customized.
special-effects-section:
  # These are the animation sets a player can choose for the warps. By default, the first in the list will be the default animation set for new warps.
  # Please follow the format <Set Name>:<Delay Type>/<Delay Effect>:<Teleport Type>/<Teleport Effect> (Note: There must be at least one animation set in the list and the set names can contain color codes).
  # Particle effects can be found here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html
  # The current types are: [CONE, HELIX, CIRCLE, VORTEX, RING]
  warp-animation-list:
    - "&fFlash Backs:CONE/CLOUD:CIRCLE/SPELL_WITCH"
    - "&6Over Drive:VORTEX/SPELL_WITCH:CIRCLE/CLOUD"
    - "&cOddly Hot:RING/FLAME:CIRCLE/FLAME"
  # This is the animation that is displayed when the player is successfully teleported through a standalone teleportation command such as /TP or /TPO.
  # (Format: <type>:<effect>) Particle effects can be found here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html
  # The current types are: [CONE, HELIX, CIRCLE, VORTEX, RING]
  standalone-teleport-animation: "VORTEX:FIREWORKS_SPARK"
  # This is the animation that is displayed for each player involved in a group teleport after the teleportation is complete. (Format: <type>:<effect>)
  # Particle effects can be found here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html
  # The current types are: [CONE, HELIX, CIRCLE, VORTEX, RING]
  group-teleport-animation: "VORTEX:FIREWORKS_SPARK"
  # This is the animation that is displayed when the player is successfully randomly teleported. (Format: <type>:<effect>)
  # Particle effects can be found here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html
  # The current types are: [CONE, HELIX, CIRCLE, VORTEX, RING]
  random-teleport-animation: "CIRCLE:FIREWORKS_SPARK"
  # This is the animation that is displayed when the player is successfully teleported through a standalone teleportation command such as /TP or /TPO.
  # (Format: <type>:<effect>) Particle effects can be found here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html
  # The current types are: [CONE, HELIX, CIRCLE, VORTEX, RING]
  random-teleport-delay-animation: "VORTEX:FIREWORKS_SPARK"